# Needs Xenial, not Trusty for Python 3.7 works:
# https://travis-ci.community/t/unable-to-download-python-3-7-archive-on-travis-ci/639/2
# https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-425867404
dist: xenial

# [INFO] Don't download all repository history, that save a time:
# https://docs.travis-ci.com/user/customizing-the-build/#git-clone-depth
git:
  depth: 1

language: python

python: 3.7

install:
- pip install --upgrade pip
- pip install flake8 pydocstyle pylint

script:
- flake8 .
- pydocstyle
- pylint .